apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: jenkins
spec:
  consolidation:
    enabled: true
  labels:
    jenkins: "true"
  requirements:
    - key: karpenter.sh/capacity-type         # optional, set to on-demand by default, spot if both are listed
      operator: In
      values: ["spot","on-demand"]
    - key: "kubernetes.io/arch" # If not included, the webhook for the AWS Cloud Provider will default to amd64
      operator: In
      values: ["amd64"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m6a.large"]
  taints:
  - key: jenkins
    value: "true"
    effect: "NoSchedule"
  limits:
    resources:
      cpu: 1000                               # optional, recommended to limit total provisioned CPUs
      memory: 1000Gi
  provider:    
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3                                         # optional, recommended to use instead of `provider`
    securityGroupSelector:
      aws-ids: "sg-06fa5d1dfb45ae2aa"
    subnetSelector:
      aws-ids: "subnet-06a72bdc4caf5d205,subnet-0efc2c6ca97fca509,subnet-0f95049eb7a22def7"
  # ttlSecondsAfterEmpty: 30                    # optional, but never scales down if not set
  ttlSecondsUntilExpired: 2592000
